apiVersion: apps/v1
kind: Deployment
metadata:   
  annotations:  
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas" 
  name: umd6bjc3v-java-quarkus
spec:
  replicas: 1 
  template: 
    spec:
      containers:
      - image: quay.io/rhtap_qe/rhtap-qe:ca4357ac1f10ddc99d068b592940405e35ef9b4b@sha256:64446d68dee5b7a277868a66b0f809caff2ff16233fcd4db9cb8ee9071fe87aa
        name: container-image  
